### ISSUE TITLE
Allow linking to ICU

### ISSUE THREAD

**Issue by rinigus** [sailfishos/sdk-harbour-rpmvalidator#103]
I need to link to ICU and related libraries and would like to ask to include into white listed libraries that are involved in `-licuuc` :

```
/usr/lib/libicui18n.so.52
/usr/lib/libicudata.so.52
/usr/lib/libicuuc.so.52
```

Out of these, libicudata is just big and there is no point in carrying many copies of this library on the device

**Comment by martyone** [comment]
I am sorry but as you could learn here https://lists.sailfishos.org/pipermail/devel/2017-December/008164.html I doubt this would be accepted in the visible future.

**Comment by rinigus** [comment]
Right, I managed to forget these emails about ICU. Feel free to close the issue or keep it open for years, if its better

**Comment by pvuorela** [comment]
I'll close this, don't think we can do much with the unstable ABI upstream.
