### ISSUE TITLE
Allow Nemo.KeepAlive

### ISSUE THREAD

**Issue by attah** [sailfishos/sdk-harbour-rpmvalidator#113]
The rumour on IRC is that Nemo.KeepAlive 1.1 is actually allowed, but it's not on the list.

**Comment by martyone** [comment]
There are changes required to the API in order to allow it. I am unable to give any estimation.

**Comment by attah** [comment]
Is there somewhere we can follow, or contribute to that?
If not, closing this seems a bit premature...

**Comment by martyone** [comment]
Yes, you could get better insight by asking on together.jolla.com - questions there are linked to the internal bug tracker. This issue has an internal bug tracking item that is being worked on already.
