### ISSUE TITLE
Allow new Sailfish share API (import Sailfish.Share)

### ISSUE THREAD

**Issue by Karry** [sailfishos/sdk-harbour-rpmvalidator#135]
Hi. With SFOS 4.2 there was change in sharing api. Silica page `Sailfish.TransferEngine.SharePage` is not available anymore. System applications are using new Silica component `ShareAction` from `Sailfish.Share` package now. Will be possible to use this API even for ordinary applications?

In other words, may be `Sailfish.Share` added to allowed imports?

**Comment by pvuorela** [comment]
This came fast :)

The new sharing system should be more compatible now for third party usage as the sharing is not anymore done in-process. The new API  should be also solid. There are a few internal details included on the component now but if sticking to the documented API it should be all good. For playing it a bit safer didn't yet however add it to allowed imports on the same release it was introduced in.

But now unless something special pops up quick, I wouldn't see any big reason not to allow it.

**Comment by rainemak** [comment]
Let's add it there.
